"""Shared test helpers: fixture paths and exact float64 bit decoding.

The crate-side fixtures (`CORE_FIXTURES`) are reused verbatim so the binding is
checked against the same goldens the Rust core asserts on. They are resolved, in
order, from:

1. ``SIDEREON_CORE_FIXTURES`` if set (explicit override).
2. A sibling ``sidereon-core`` checkout (in-tree development layout).
3. A local ``[patch.crates-io]`` / path dependency to ``sidereon-core``.
4. The cargo git checkout of the exact ``sidereon-core`` revision this binding
   is locked to (parsed from ``Cargo.lock``), so the fixtures always match the
   core the extension was built against.
"""

import datetime as dt
import os
import re
import struct

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.normpath(os.path.join(_HERE, ".."))

# Binding-local fixtures generated by the env-gated dump in the crate's
# rtk_real_arc / ppp_real_arc integration tests (see tests/fixtures/README.md).
FIXTURES = os.path.join(_HERE, "fixtures")


def _locked_core_rev():
    """The sidereon-core git revision this binding is locked to, or None."""
    lock = os.path.join(_REPO, "Cargo.lock")
    try:
        with open(lock) as handle:
            text = handle.read()
    except OSError:
        return None
    for block in text.split("[[package]]"):
        if 'name = "sidereon-core"' not in block:
            continue
        match = re.search(r'source = "git\+[^"]*#([0-9a-f]+)"', block)
        if match:
            return match.group(1)
    return None


def _cargo_checkout_fixtures():
    """Fixtures dir inside the cargo git checkout of the locked core rev."""
    rev = _locked_core_rev()
    if not rev:
        return None
    root = os.path.expanduser("~/.cargo/git/checkouts")
    if not os.path.isdir(root):
        return None
    for entry in os.listdir(root):
        if not entry.startswith("sidereon-"):
            continue
        # cargo names the checkout directory with the short (7-char) revision.
        cand = os.path.join(
            root, entry, rev[:7], "crates", "sidereon-core", "tests", "fixtures"
        )
        if os.path.isdir(cand):
            return cand
    return None


def _path_dependency_fixtures():
    """Fixtures dir from a local sidereon-core path dependency."""
    for config in (
        os.path.join(_REPO, "Cargo.toml"),
        os.path.join(_REPO, ".cargo", "config.toml"),
    ):
        try:
            with open(config) as handle:
                text = handle.read()
        except OSError:
            continue
        match = re.search(r'sidereon-core\s*=\s*\{\s*path\s*=\s*"([^"]+)"', text)
        if not match:
            continue
        path = os.path.expanduser(match.group(1))
        if not os.path.isabs(path):
            path = os.path.normpath(os.path.join(_REPO, path))
        cand = os.path.join(path, "tests", "fixtures")
        if os.path.isdir(cand):
            return cand
    return None


def _resolve_core_fixtures():
    override = os.environ.get("SIDEREON_CORE_FIXTURES")
    if override:
        return override

    sibling_candidates = (
        # The standard workspace layout keeps the binding and Rust repositories
        # beside each other under one parent directory.
        os.path.join(
            _HERE,
            "..",
            "..",
            "sidereon",
            "crates",
            "sidereon-core",
            "tests",
            "fixtures",
        ),
        # Also accept a standalone sidereon-core checkout beside this repository.
        os.path.join(_HERE, "..", "..", "sidereon-core", "tests", "fixtures"),
    )
    for sibling in sibling_candidates:
        sibling = os.path.normpath(sibling)
        if os.path.isdir(sibling):
            return sibling

    path_dep = _path_dependency_fixtures()
    if path_dep:
        return path_dep

    checkout = _cargo_checkout_fixtures()
    if checkout:
        return checkout

    raise RuntimeError(
        "could not locate sidereon-core test fixtures; set SIDEREON_CORE_FIXTURES "
        "to the crate's tests/fixtures directory"
    )


def __getattr__(name):
    # Resolve CORE_FIXTURES lazily (PEP 562): importing this module only for the
    # binding-local FIXTURES path or hex_to_f64 must not require the crate-side
    # goldens, which are absent from the published sidereon-core package. Only a
    # test that actually references CORE_FIXTURES triggers resolution (and raises
    # if the crate fixtures are unavailable).
    if name == "CORE_FIXTURES":
        return _resolve_core_fixtures()
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def hex_to_f64(s):
    """Decode a `0x...` big-endian IEEE-754 float64 bit pattern to a Python float."""
    return struct.unpack(">d", struct.pack(">Q", int(s, 16)))[0]


def sp3_bytes_for_date(content, date, agency="AIUB"):
    """Shift the committed full-day SP3 fixture to a catalog-supported date."""
    lines = content.decode("ascii").splitlines()
    first_fields = lines[0][3:31].split()
    original = dt.datetime(
        int(first_fields[0]),
        int(first_fields[1]),
        int(first_fields[2]),
        int(first_fields[3]),
        int(first_fields[4]),
    )
    target = dt.datetime(date.year, date.month, date.day)
    delta = target - original

    def epoch_prefix(marker, value):
        return (
            f"{marker}{value.year:4d}{value.month:3d}{value.day:3d}"
            f"{value.hour:3d}{value.minute:3d}"
            f"{value.second + value.microsecond / 1_000_000:12.8f}"
        )

    lines[0] = epoch_prefix(lines[0][:3], target) + lines[0][31:-4] + f"{agency:>4}"
    gps_seconds = int((target.date() - dt.date(1980, 1, 6)).days) * 86_400
    gps_week, tow = divmod(gps_seconds, 7 * 86_400)
    mjd = (target.date() - dt.date(1858, 11, 17)).days
    cadence = float(lines[1][24:38])
    lines[1] = (
        f"## {gps_week:4d} {float(tow):14.8f} {cadence:14.8f} {mjd:5d} {0.0:15.13f}"
    )
    for index, line in enumerate(lines):
        if not line.startswith("*  "):
            continue
        fields = line[3:31].split()
        epoch = dt.datetime(
            int(fields[0]),
            int(fields[1]),
            int(fields[2]),
            int(fields[3]),
            int(fields[4]),
        ) + dt.timedelta(seconds=float(fields[5]))
        shifted = epoch + delta
        lines[index] = epoch_prefix("*  ", shifted) + line[31:]
    return ("\n".join(lines) + "\n").encode("ascii")
