"""Shared test helpers: fixture paths and exact float64 bit decoding.

The crate-side fixtures (`CORE_FIXTURES`) are reused verbatim so the binding is
checked against the same goldens the Rust core asserts on. They are resolved, in
order, from:

1. ``SIDEREON_CORE_FIXTURES`` if set (explicit override).
2. A sibling ``sidereon-core`` checkout (in-tree development layout).
3. The cargo git checkout of the exact ``sidereon-core`` revision this binding
   is locked to (parsed from ``Cargo.lock``), so the fixtures always match the
   core the extension was built against.
"""

import os
import re
import struct

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.normpath(os.path.join(_HERE, ".."))

# Binding-local fixtures generated by the env-gated dump in the crate's
# rtk_real_arc / ppp_real_arc integration tests (see tests/fixtures/README.md).
FIXTURES = os.path.join(_HERE, "fixtures")


def _locked_core_rev():
    """The sidereon-core git revision this binding is locked to, or None."""
    lock = os.path.join(_REPO, "Cargo.lock")
    try:
        with open(lock) as handle:
            text = handle.read()
    except OSError:
        return None
    for block in text.split("[[package]]"):
        if 'name = "sidereon-core"' not in block:
            continue
        match = re.search(r'source = "git\+[^"]*#([0-9a-f]+)"', block)
        if match:
            return match.group(1)
    return None


def _cargo_checkout_fixtures():
    """Fixtures dir inside the cargo git checkout of the locked core rev."""
    rev = _locked_core_rev()
    if not rev:
        return None
    root = os.path.expanduser("~/.cargo/git/checkouts")
    if not os.path.isdir(root):
        return None
    for entry in os.listdir(root):
        if not entry.startswith("sidereon-"):
            continue
        # cargo names the checkout directory with the short (7-char) revision.
        cand = os.path.join(
            root, entry, rev[:7], "crates", "sidereon-core", "tests", "fixtures"
        )
        if os.path.isdir(cand):
            return cand
    return None


def _resolve_core_fixtures():
    override = os.environ.get("SIDEREON_CORE_FIXTURES")
    if override:
        return override

    sibling = os.path.normpath(
        os.path.join(
            _HERE, "..", "..", "..", "crates", "sidereon-core", "tests", "fixtures"
        )
    )
    if os.path.isdir(sibling):
        return sibling

    checkout = _cargo_checkout_fixtures()
    if checkout:
        return checkout

    raise RuntimeError(
        "could not locate sidereon-core test fixtures; set SIDEREON_CORE_FIXTURES "
        "to the crate's tests/fixtures directory"
    )


def __getattr__(name):
    # Resolve CORE_FIXTURES lazily (PEP 562): importing this module only for the
    # binding-local FIXTURES path or hex_to_f64 must not require the crate-side
    # goldens, which are absent from the published sidereon-core package. Only a
    # test that actually references CORE_FIXTURES triggers resolution (and raises
    # if the crate fixtures are unavailable).
    if name == "CORE_FIXTURES":
        return _resolve_core_fixtures()
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def hex_to_f64(s):
    """Decode a `0x...` big-endian IEEE-754 float64 bit pattern to a Python float."""
    return struct.unpack(">d", struct.pack(">Q", int(s, 16)))[0]
